### ISSUE TITLE
No audio in some videos 

### ISSUE THREAD

**Issue by zeex-pro** [HamidrezaAmz/MagicalExoPlayer#10]
Hello.

I have a issue with playing audio in some videos. I think player is missing some codecs. Most of the the videos play perfect but some with no sound only video. The same videos working in vlc on my laptop with sound but no sound in magical player. I think it is codecs issue.

**Comment by HamidrezaAmz** [comment]
Can you give me an example link? let me test it

**Comment by zeex-pro** [comment]
For example:

http://ksportiptv.com:1557/live/Blaz/Sk0t4La5Qh/13075.m3u8

Video is playing but not audio. Audio codec is  MPEG Audio layer 1/2 (mpga)

**Comment by HamidrezaAmz** [comment]
hi @fuqet90 

The link you provide is denying my access.

And also checkout this issue [https://github.com/google/ExoPlayer/issues/501](https://github.com/google/ExoPlayer/issues/501) on ExoPlayer library, they are just support ` 0x0F (AAC)` for audio stream type.
