### ISSUE TITLE
add dependency

### ISSUE THREAD

**Issue by NoSratii** [HamidrezaAmz/MagicalExoPlayer#11]
سلام من توی اضافه کردن لایبرری به پروژه ام مشکل دارم ممنون میشم راهنماییم کنید ..
Nosrati.shiva92@gmail.com

**Comment by HamidrezaAmz** [comment]
Hi @NoSratii 
MagicalExoPlyer is a gradle base library, you need to add library dependencies into your project's gradle file.
There is an example for you in `Installing` section of readme. Check it out.
