### ISSUE TITLE
حذف کنترلها یا تغییر کنترل ویو

### ISSUE THREAD

**Issue by ali-bagheri** [HamidrezaAmz/MagicalExoPlayer#2]
سلام و تشکر از کتابخونه خوبت
آیا امکان دارد تمامی کنترل ها را محو کنیم؟
آیا امکان دارد کنترل ویو سفارشی داشته باشیم؟

**Comment by HamidrezaAmz** [comment]
Hi. 
Yes, for hiding controllers you can use `andExoPlayerView.hideController();`
For custom controller just introduce your need, I will implement that as soon as possible.
