### ISSUE TITLE
No AndroidX

### ISSUE THREAD

**Issue by mohammadarbabi74** [HamidrezaAmz/MagicalExoPlayer#22]
Is it possible use it on support library?

**Comment by HamidrezaAmz** [comment]
what do you mean by use on support library?!!!

**Comment by mohammadarbabi74** [comment]
salam man az androidX estefade nemikonam rahi nadare beshe azesh estefade kard?

**Comment by HamidrezaAmz** [comment]
Hi bro.
As an android developer, I strongly suggest you to switch into androidX as soon as possible ;)
