### ISSUE TITLE
HLS format cannot be played, prompt to try again

### ISSUE THREAD

**Issue by liuyanshen6** [HamidrezaAmz/MagicalExoPlayer#23]
Hi Excuse me? HLS format cannot be played, prompt to try again  Why? Is there something missing? How can I solve it We look forward to your reply
![image](https://user-images.githubusercontent.com/46120958/79090202-73794c00-7d7b-11ea-8871-707b3c4c42a0.png)

**Comment by HamidrezaAmz** [comment]
Hey @liuyanshen6 
New version of **MagicalExoPlayer** is released, HLS test link is available in test app. check it out ;)
