### ISSUE TITLE
Default interface methods are only supported starting with Android N (--min-api 24)

### ISSUE THREAD

**Issue by karagarwal** [HamidrezaAmz/MagicalExoPlayer#26]
After implementing while building the application getting the following errors:

1.  Default interface methods are only supported starting with Android N (--min-api 24): java.lang.CharSequence com.google.android.exoplayer2.ui.PlayerNotificationManager$MediaDescriptionAdapter.getCurrentSubText(com.google.android.exoplayer2.Player)

2. Default interface methods are only supported starting with Android N (--min-api 24): void com.google.android.exoplayer2.Player$EventListener.onIsPlayingChanged(boolean)

3. Invoke-customs are only supported starting with Android O (--min-api 26)

**Comment by m9yaseen** [comment]
> After implementing while building the application getting the following errors:
> 
> 1. Default interface methods are only supported starting with Android N (--min-api 24): java.lang.CharSequence com.google.android.exoplayer2.ui.PlayerNotificationManager$MediaDescriptionAdapter.getCurrentSubText(com.google.android.exoplayer2.Player)
> 2. Default interface methods are only supported starting with Android N (--min-api 24): void com.google.android.exoplayer2.Player$EventListener.onIsPlayingChanged(boolean)
> 3. Invoke-customs are only supported starting with Android O (--min-api 26)

hello , you have problem with compile time , make sure you have add this code to your app level gradle 

android {
...
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
...
}
