### ISSUE TITLE
Not working in raw files videos and live url also. 

### ISSUE THREAD

**Issue by DaxeshV** [HamidrezaAmz/MagicalExoPlayer#29]
Not working in raw files videos and live url also. 

https://sample-videos.com/video123/mp4/360/big_buck_bunny_360p_10mb.mp4

**Comment by HamidrezaAmz** [comment]
I have test your url, and every thing is good. check your internet connection @DaxeshV 

<img width="377" alt="Screen Shot 2021-05-03 at 12 09 02" src="https://user-images.githubusercontent.com/13493645/116851438-9802c900-ac07-11eb-9531-d23b71e9d372.png">
