### ISSUE TITLE
Remove timer

### ISSUE THREAD

**Issue by zeex-pro** [HamidrezaAmz/MagicalExoPlayer#3]
Hello.

How can I remove time stamps while playing videos? Player works well. I just looking for solution to remove timer on both sides of time line.

**Comment by HamidrezaAmz** [comment]
Hi
So you need a new design with just play/pause button and timeline or hide the controller?

**Comment by zeex-pro** [comment]
Hi.

I need hide the controller. 

Thanks

**Comment by HamidrezaAmz** [comment]
For hiding controllers you can use `andExoPlayerView.hideController();`
This method will hide all of the player controller.

**Comment by zeex-pro** [comment]
I have added andExoPlayerView.hideController(); but it doesn't hide controls. Is there any other way to do this? Or how I can control exoplayer through andexoplayer. I can not find any solution.

Thanks for your answer.

**Comment by HamidrezaAmz** [comment]
I have added new property name `andexo_show_controller` for show/hide player controller . just update your `MagicalExoPlayer` to the latest version and pass `andexo_show_controller` in `XML`. Example is in readme. ;)

Have FUN

**Comment by zeex-pro** [comment]
Sorted! 
Thank you very much.

**Comment by tamselvan89** [comment]
@HamidrezaAmz andexo_show_controller  this one is not working. Still am seeing the controls while playing video.
