### ISSUE TITLE
Are there any callbacks here?

### ISSUE THREAD

**Issue by edward1988** [HamidrezaAmz/MagicalExoPlayer#31]
Hi, thanks for your awesome player, but i need to know when video is over or video loaded or something else. Can i get some callback from this player?

**Comment by chitgoks** [comment]
looking for the same thing

**Comment by HamidrezaAmz** [comment]
Hey @chitgoks @edward1988 
New version of magicalExoPlayer is released.

You can use **AndExoPlayerListener** and use callbacks that available there.

`  
    fun onExoPlayerStart() {}

    fun onExoPlayerFinished() {}

    fun onExoPlayerLoading() {}

    fun onExoPlayerError(errorMessage: String?) {}

    fun onExoBuffering() {}

    fun onExoEnded() {}

    fun onExoIdle() {}

    fun onExoReady() {}

`
