### ISSUE TITLE
Error inflating class com.potyvideo.library.AndExoPlayerView

### ISSUE THREAD

**Issue by SurajC23** [HamidrezaAmz/MagicalExoPlayer#38]
I want to use AndExoPlayerView but every time i get this error

**Comment by mobileservicepv** [comment]
Have you added "**compileOptions**" in your app Gradle file?

**Comment by Prachidighe** [comment]
Have you added "compileOptions" in your app Gradle file?

**Comment by Abrar-ul-haq-Abro** [comment]
> Have you added "compileOptions" in your app Gradle file?

how to add compile options.....which option to add....and where

**Comment by Abrar-ul-haq-Abro** [comment]
Solved....
thanks prachidghe.....
added compile options....
for those having same problem add below code in build.gradle app file....
   compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
