### ISSUE TITLE
Create key-value map for the HTTP headers

### ISSUE THREAD

**Issue by hieulbp** [HamidrezaAmz/MagicalExoPlayer#4]
Can you update the header when playing hls video? like this:
Map <String, String> header = new HashMap <> ();
header.put ("cookie", "abcd1234");
andExoPlayerView.addHeader(header);

tks you very much <3

**Comment by hieulbp** [comment]
No error message when link error and more dialog loading while waiting for video play will be great!

**Comment by HamidrezaAmz** [comment]
Yep! I will add these futures as soon as possible ;)

**Comment by hieulbp** [comment]
> Yep! I will add these futures as soon as possible ;)

that's great!

**Comment by HamidrezaAmz** [comment]
Hi
New version is available, **Retry button** for link error, **progress** for waiting for video play added.
For **custom headers** now you can pass them with your source like this:

```java
  HashMap<String , String> extraHeaders = new HashMap<>();
  extraHeaders.put("foo","bar");
  andExoPlayerView.setSource("STREAM_URL", extraHeaders);
```

have fun ;)

**Comment by hieulbp** [comment]
> Hi
> New version is available, **Retry button** for link error, **progress** for waiting for video play added.
> For **custom headers** now you can pass them with your source like this:
> 
> ```java
>   HashMap<String , String> extraHeaders = new HashMap<>();
>   extraHeaders.put("foo","bar");
>   andExoPlayerView.setSource("STREAM_URL", extraHeaders);
> ```
> 
> have fun ;)

tks u ^^

**Comment by hieulbp** [comment]
> Hi
> New version is available, **Retry button** for link error, **progress** for waiting for video play added.
> For **custom headers** now you can pass them with your source like this:
> 
> ```java
>   HashMap<String , String> extraHeaders = new HashMap<>();
>   extraHeaders.put("foo","bar");
>   andExoPlayerView.setSource("STREAM_URL", extraHeaders);
> ```
> 
> have fun ;)

How to onPlayerError in MainActivity?

**Comment by HamidrezaAmz** [comment]
For new futures please create a new **issue**, this will help other users find their need faster and easier.
