### ISSUE TITLE
video is showing very dark

### ISSUE THREAD

**Issue by syedumair123** [HamidrezaAmz/MagicalExoPlayer#41]
brightness is very low of video

**Comment by HamidrezaAmz** [comment]
Check your phone's brightness buddy ;)

**Comment by syedumair123** [comment]
i have tested it on many phones your repo is outstanding and i appreciate your hardwork but i have tested it on many phones and still the issue of brightness is there , can you please tell me is there any property to increase the brightness of video

________________________________

**Comment by HamidrezaAmz** [comment]
Can you give me your test url?
