### ISSUE TITLE
Problem when used in recyclerview

### ISSUE THREAD

**Issue by vivekbdc** [HamidrezaAmz/MagicalExoPlayer#45]
I used this library in recyclerview. but not working recyclerview adapter. 
My app is a social media app and I used this player in story view. 

Please advise if there is any solution is available.

`holder.binding.videoPlayer.setSource("video_url");`

**Comment by chenzhenyu** [comment]
I have the same question, and I guess "SimpleExoPlayer" recycled by the RecyclerView, I just wonder how to reinit.

**Comment by chenzhenyu** [comment]
I find a template way to solve this question. The question was caused by "AndExoPlayerView" overrides "onDetachedFromWindow". In this method, the author invokes releasePlayer(). So, just extend "AndExoPlayerView", not invoke super(). If you have the better solution, hope you could share.

**Comment by chenzhenyu** [comment]
I find a temporary way to solve this question. The question was caused by "AndExoPlayerView" overrides "onDetachedFromWindow". In this method, the author invokes releasePlayer(). So, just extend "AndExoPlayerView", not invoke super(). If you have the better solution, hope you could share.

**Comment by vivekbdc** [comment]
Thanks for sharing your thoughts, but I changed my library and now using https://github.com/google/ExoPlayer supported by google.
