### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.exoplayergithub/com.example.exoplayergithub.MainActivity}: android.view.InflateException

### ISSUE THREAD

**Issue by Kanishk251296** [HamidrezaAmz/MagicalExoPlayer#48]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.exoplayergithub/com.example.exoplayergithub.MainActivity}: android.view.InflateException

Getting this error on opening the app

**Comment by HamidrezaAmz** [comment]
hey @Kanishk251296 
New version of MagicalExoPlayer is released, update ;)
