### ISSUE TITLE
layout/layout_player_base: Error inflating class com.google.android.exoplayer2.ui.SimpleExoPlayerView

### ISSUE THREAD

**Issue by codaman** [HamidrezaAmz/MagicalExoPlayer#55]
I got this error when inflating.
I already added 

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
but still crashing.

There is no problem with this dependency 'com.google.android.exoplayer:exoplayer:2.11.1'

but crashing new version on exoplayer
'com.google.android.exoplayer:exoplayer:2.13.3'

**Comment by codaman** [comment]
This is work fine with little changes on layout_player_base.xml

```
<com.google.android.exoplayer2.SimpleExoPlayerView
        android:id="@+id/simpleExoPlayerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:controller_layout_id="@layout/video_player_exo_controllers" />
```

to

```
<com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/simpleExoPlayerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:controller_layout_id="@layout/video_player_exo_controllers" />
```

**Comment by HamidrezaAmz** [comment]
Hi @codaman 
I have updated `ExoPlayer` core into newer version, just update `MagicalExoPlayer`
