### ISSUE TITLE
Unable to publish as a dependency in a library

### ISSUE THREAD

**Issue by ghost** [HamidrezaAmz/MagicalExoPlayer#56]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':common:debugCompileClasspath'.
   > Could not find com.sdsmdg.tastytoast:tastytoast:0.1.1.
     Required by:
         project :common
   > Could not find com.google.android.exoplayer:exoplayer:2.13.2.
     Required by:
         project :common > com.github.HamidrezaAmz:MagicalExoPlayer:2.0.6
   > Could not find com.google.android.exoplayer:exoplayer-ui:2.13.2.
     Required by:
         project :common > com.github.HamidrezaAmz:MagicalExoPlayer:2.0.6
   > Could not find com.google.android.exoplayer:exoplayer-hls:2.13.2.
     Required by:
         project :common > com.github.HamidrezaAmz:MagicalExoPlayer:2.0.6
   > Could not find com.google.android.exoplayer:exoplayer-dash:2.13.2.
     Required by:
         project :common > com.github.HamidrezaAmz:MagicalExoPlayer:2.0.6
`

**Comment by HamidrezaAmz** [comment]
Updated `ExoPlayer` core to the newer version.
