### ISSUE TITLE
Missing headers parameter since 2.x

### ISSUE THREAD

**Issue by andlinger** [HamidrezaAmz/MagicalExoPlayer#58]
With version 1.x it was possible to include HTTP headers in the setSource method. This parameter is missing since version 2.x

**Comment by HamidrezaAmz** [comment]
Hey @andlinger 
Yes it's under develop, and will be added soon into version 2.x

**Comment by HamidrezaAmz** [comment]
@andlinger 
Custom Header Support added into V2 versions of MagicalExoPlayer. 
Update to new version and use it ;)
