### ISSUE TITLE
setPlayWhenReady(false) not working 

### ISSUE THREAD

**Issue by redviper2017** [HamidrezaAmz/MagicalExoPlayer#60]
I am using the player in recyclerview item and even after setting setPlayWhenReady(false), all the videos starts play as soon as they are loaded. Need help to stop this.

**Comment by sudarshaana** [comment]
Same here. I'm using `2.14.0`

**Comment by HamidrezaAmz** [comment]
Hi @redviper2017 
I have fixed this issue, just update `MagicalExoPlayer` to the newest version.
