### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: com.potyvideo.library.AndExoPlayerView.onPlayerError (AndExoPlayerView.java:1)

### ISSUE THREAD

**Issue by ghost** [HamidrezaAmz/MagicalExoPlayer#63]
i have an issue is sometime my app crash when i tap to play video
this is my firebase log: 
`com.google.android.exoplayer2.util.Assertions.checkState (Assertions.java:5)
com.google.android.exoplayer2.ExoPlaybackException.getSourceException (ExoPlaybackException.java:1)
com.potyvideo.library.AndExoPlayerView.onPlayerError (AndExoPlayerView.java:1)
com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$9 (ExoPlayerImpl.java:1)
com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$Y5tnvNJdNEscTPhujmeSdRy1n7Y.invoke (-.java:1)
com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke (ListenerSet.java:4)
com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0 (ListenerSet.java:4)
com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run (-.java:4)
com.google.android.exoplayer2.util.ListenerSet.flushEvents (ListenerSet.java:2)
com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:2)
com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo (ExoPlayerImpl.java:5)
com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$nOBJYkeEQ2uz3sBKLToLWmzrgZk.run (-.java:5)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:263)
android.app.ActivityThread.main (ActivityThread.java:8267)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:612)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1006)`

In my programmatically, i have calls startPlayer() in onStart() callback and pausePlayer() in onStop()
`andExoPlayerView.startPlayer()` `andExoPlayerView.pausePlayer()`
in addition, i calls setSource() inside BindingAdapter file
`view.setSource(url)`

anyone can help me, pls?
this really is urgent issue

**Comment by ghost** [comment]
crash occurs at line `com.potyvideo.library.AndExoPlayerView.onPlayerError (AndExoPlayerView.java:1)`

**Comment by HamidrezaAmz** [comment]
Hi @baonq-2356 
I think you are `startPlayer ()` before `setSource(url)`
set source should call before start player or other functions.

**Comment by ghost** [comment]
@HamidrezaAmz yepp, i see `startPlayer ()` run before `setSource(url)` when i get log. But in some case, my app still works, sometimes not. Can you give me more infomation to guaranteed this issue will not repeat, pls?

**Comment by HamidrezaAmz** [comment]
@baonq-2356 you can checkout sample project in the repo

**Comment by ghost** [comment]
@HamidrezaAmz i tried your suggestion, but my app still crash :\

**Comment by ghost** [comment]
hello @HamidrezaAmz 
i received a suggestion for my issue from owner of `ExoPlayer`, he advised to report this issue to you, details what happens wrong in here:
https://github.com/google/ExoPlayer/issues/9330#issuecomment-910148660
Can you help me check it, pls

**Comment by phucnv-2558** [comment]
@HamidrezaAmz This may be because the release time is too short, can you increase it from 500ms to 1000ms? or in your library is it possible to make players public?

**Comment by HamidrezaAmz** [comment]
Hi @baonq-2356 
`onPlayerError` is deprecated, I have update `ExoPlayer` core and implemented new interface for `onPlayerError`
Just update library into newest version.
