### ISSUE TITLE
None of the available extractors

### ISSUE THREAD

**Issue by RedaMohsen** [HamidrezaAmz/MagicalExoPlayer#66]
Hello
I am having an issue when trying to load a video from Youtube and it reads : None of the available extractors
I have uploaded a MP4 format video to test 
Please let me know if there is a specific params passed in the hashmap in setSource method

**Comment by em-ad** [comment]
Youtube uses objects that contain streaming objects
If you process your URL request and look at the http response in the Inspect->Network->Response section in the browser, you'll see that the link doesn't respond with a hls link, but the respond contains a large object, parsable by the youtube website or application.
In short, this library doesn't process and load youtube videos as is
