### ISSUE TITLE
Class not found in compose project

### ISSUE THREAD

**Issue by harishpadmanabh-HP** [HamidrezaAmz/MagicalExoPlayer#68]
I have integrated the dependancies but the class ANdExoPLayer is not found

**Comment by em-ad** [comment]
Please copy the dump or log of the build process here

**Comment by HamidrezaAmz** [comment]
Hi @harishpadmanabh-HP 
I have update `ExoPlayer` core, just update `MagicalExoPlayer` to the newest version
