### ISSUE TITLE
recyclerview

### ISSUE THREAD

**Issue by MSoltanieh** [HamidrezaAmz/MagicalExoPlayer#69]
سلام، وقتی تو ریسایکلرویو استفاده میکنیم با بالا و پایین کردن صفحه انگار منبع پخش و لینک پخش دیگه لود نمیشه. آیا تنظیم خاصی داره ؟

**Comment by em-ad** [comment]
با سلام
 اگر اونقدری لیست رو پایین برید که آیتم لیست دوباره بایند بشه، طبیعتا هر اطلاعاتی توی ویوهلدر هست دیگه قابل اتکا نیست و باید دوباره بایند بشه
میتونید جلوی ریسایکل (بازیافت) شدن ویوها رو بگیرید یا آیتم پخش کننده ویدیو رو در یک اسکپ بالاتر تعریف کنید
