### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by zeex-pro** [HamidrezaAmz/MagicalExoPlayer#7]
Hello.

I was wondering, if there is any option to enable or integrate chromecast while watching videos?

Thanks

**Comment by HamidrezaAmz** [comment]
Hi
What do you mean by `enable or integrate chromecast while watching videos`?
you mean enabling screen mirroring? or Smart View? or some thing like this?

**Comment by zeex-pro** [comment]
Yes I would like to enable screen mirroring while I watching videos.

**Comment by HamidrezaAmz** [comment]
Sry, Enabling screen mirroring is not the objective of this project.
