### ISSUE TITLE
setPlayWhenIsReady(false) not working

### ISSUE THREAD

**Issue by MasudRhmi** [HamidrezaAmz/MagicalExoPlayer#71]
سلام دوست عزیز
این مشکل رو چطور میشه رفع کرد؟

**Comment by HamidrezaAmz** [comment]
Hi @MasudRhmi 
I will check it as soon as possible.

**Comment by ilkeryildirim** [comment]
@HamidrezaAmz did you check?

**Comment by HamidrezaAmz** [comment]
Hi @MasudRhmi & @ilkeryildirim 
Fixed `setPlayWhenIsReady ` issue, just update to new version.
