### ISSUE TITLE
Not managing or not setting Headers

### ISSUE THREAD

**Issue by ihasanazimi** [HamidrezaAmz/MagicalExoPlayer#72]
Salam hamidReza jan
azizm man daqiqan eyn document ro piyade kardam ama moshkel injast k heaser vasash set nemishe!!!
mishe ye dasti az ma beghiri?

**Comment by HamidrezaAmz** [comment]
Hi @ihasanazimi 
Can you give me a sample link for test?

**Comment by HamidrezaAmz** [comment]
Added in new version ( 3.0.3 )
