### ISSUE TITLE
Version Issue  - MagicalExoPlayer:3.0.3

### ISSUE THREAD

**Issue by poorankharol** [HamidrezaAmz/MagicalExoPlayer#78]
Kindly release v3.0.3 or update the readme because when someone tries to use v3.0.3 it throws an error.

**Failed to resolve: com.github.HamidrezaAmz:MagicalExoPlayer:3.0.3**

**Comment by HamidrezaAmz** [comment]
Thanks, I have updated the version. now new version is up.
