### ISSUE TITLE
set TimeOut

### ISSUE THREAD

**Issue by hieulbp** [HamidrezaAmz/MagicalExoPlayer#8]
how to set time out when play streaming video

**Comment by HamidrezaAmz** [comment]
It is set to default value of `DefaultHttpDataSource` connect/read timeout value. 
You can find more [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.html#DEFAULT_CONNECT_TIMEOUT_MILLIS)
